using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProvexApi.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CloudFruitItems",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    PlanillaDespacho = table.Column<int>(type: "int", nullable: false),
                    PlanillaOrdenEmbarque = table.Column<int>(type: "int", nullable: false),
                    CodTipoNave = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomTipoNave = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodNave = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomNave = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomPais = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodPuerto = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomPuerto = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GuiaDespacho = table.Column<double>(type: "float", nullable: false),
                    FechaDespacho = table.Column<DateTime>(type: "datetime2", nullable: false),
                    HoraDespacho = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Contenedor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RutTransportista = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomTransportista = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RutChofer = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomChofer = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Patente = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FolioSAG = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Sellos = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodFacilitie = table.Column<double>(type: "float", nullable: true),
                    NomFacilitie = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BookingAwb = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Ubicacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodTipoInspeccionEnc = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomTipoInspeccionEnc = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RutRecibidor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodRecibidor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomRecibidor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RutExportador = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomExportador = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TipoCamion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RutAgenteAduana = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomAgenteAduana = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Consignatario = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Celular = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ObsSAG = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ObsGuia = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Despachador = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TipoContenedor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodTipoInspeccion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomTipoInspeccion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Pallet = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TipoPallet = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodBasePallet = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomBasePallet = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodEspecie = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomEspecie = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodTipoTrat = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomTipoTrat = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Temperatura = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Altura = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Termografo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IdPallet = table.Column<double>(type: "float", nullable: true),
                    TotalCajas = table.Column<int>(type: "int", nullable: true),
                    TotalDet = table.Column<int>(type: "int", nullable: true),
                    Mixs = table.Column<int>(type: "int", nullable: true),
                    RutProductorReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomProductorReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumeroCertificadoProductorReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TipoCertificadoProductorReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RutProductorEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomProductorEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NumeroCertificadoProductorEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TipoCertificadoProductorEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodPredioReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodPredioEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomPredioReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomPredioEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodCuartelReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodCuartelEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomCuartelReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomCuartelEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodGrpoVariedadReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodVariedadReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodGrpoVariedadEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodVariedadEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomGrpoVariedadReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomVariedadReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomGrpoVariedadEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomVariedadEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodEnvop = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomEnvop = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PesoNeto = table.Column<double>(type: "float", nullable: false),
                    CodEnvase = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomEnvase = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodEmbalaje = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomEmbalaje = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodEtiqueta = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomEtiqueta = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodCategoria = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomCategoria = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodCalibre = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomCalibre = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodPLU = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomPLU = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FechaPack = table.Column<DateTime>(type: "datetime2", nullable: true),
                    FechaCosecha = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Cajas = table.Column<int>(type: "int", nullable: true),
                    CodigoProductorReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoProductorEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AñoDespacho = table.Column<int>(type: "int", nullable: true),
                    MesDespacho = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CSG = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoGrupoProductor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NombreGrupoProductor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PesoBrutoAduana = table.Column<double>(type: "float", nullable: true),
                    CodFacilitieDestino = table.Column<double>(type: "float", nullable: true),
                    NomFacilitieDestino = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CajasEquivalentes = table.Column<double>(type: "float", nullable: true),
                    FechaEtaReal = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CodPuertoDestino = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NomPuertoDestino = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FechaZarpe = table.Column<DateTime>(type: "datetime2", nullable: true),
                    NombreMercadoNave = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FechaArribo = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ClaveEmbarque = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SemanaZarpe = table.Column<int>(type: "int", nullable: true),
                    NombreEmbarcador = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoTemporada = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoEmpresa = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NombreEmpresa = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NroProceso = table.Column<int>(type: "int", nullable: true),
                    CodigoGrupoRecibidor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NombreGrupoRecibidor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoGrupoCalibre = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NombreGrupoCalibre = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoGrupoCategoria = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NombreGrupoCategoria = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IdCategoria = table.Column<double>(type: "float", nullable: true),
                    CodFacilitiePallet = table.Column<double>(type: "float", nullable: true),
                    NomFacilitiePallet = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TipoMovimiento = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FechaInspeccion = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CodigoMercadoNave = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoExportador = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoNaviera = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NombreNaviera = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoProvinciaProdReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ProvinciaProdReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoComunaProdReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ComunaProdReal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoProvinciaProdEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ProvinciaProdEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoComunaProdEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ComunaProdEti = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NotaVenta = table.Column<int>(type: "int", nullable: true),
                    CertificadoFumigacion = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodigoPaisNave = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PaisNave = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EstibaEnCamara = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CloudFruitItems", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CloudFruitItems");
        }
    }
}
