// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvexApi.Data;

#nullable disable

namespace ProvexApi.Migrations
{
    [DbContext(typeof(ProvexDbContext))]
    [Migration("20250217185929_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvexApi.Models.CloudFruitItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Altura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AñoDespacho")
                        .HasColumnType("int");

                    b.Property<string>("BL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingAwb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CSG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Cajas")
                        .HasColumnType("int");

                    b.Property<double?>("CajasEquivalentes")
                        .HasColumnType("float");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificadoFumigacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaveEmbarque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodBasePallet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCuartelEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCuartelReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodEmbalaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodEnvase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodEnvop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodEspecie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodEtiqueta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("CodFacilitie")
                        .HasColumnType("float");

                    b.Property<double?>("CodFacilitieDestino")
                        .HasColumnType("float");

                    b.Property<double?>("CodFacilitiePallet")
                        .HasColumnType("float");

                    b.Property<string>("CodGrpoVariedadEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodGrpoVariedadReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodNave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodPLU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodPredioEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodPredioReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodPuerto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodPuertoDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodRecibidor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodTipoInspeccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodTipoInspeccionEnc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodTipoNave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodTipoTrat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodVariedadEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodVariedadReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoComunaProdEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoComunaProdReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoExportador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoGrupoCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoGrupoCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoGrupoProductor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoGrupoRecibidor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoMercadoNave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoNaviera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPaisNave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoProductorEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoProductorReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoProvinciaProdEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoProvinciaProdReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoTemporada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComunaProdEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComunaProdReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consignatario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contenedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despachador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstibaEnCamara")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaArribo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCosecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDespacho")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEtaReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInspeccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPack")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaZarpe")
                        .HasColumnType("datetime2");

                    b.Property<string>("FolioSAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GuiaDespacho")
                        .HasColumnType("float");

                    b.Property<string>("HoraDespacho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("IdCategoria")
                        .HasColumnType("float");

                    b.Property<double?>("IdPallet")
                        .HasColumnType("float");

                    b.Property<string>("MesDespacho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Mixs")
                        .HasColumnType("int");

                    b.Property<string>("NomAgenteAduana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomBasePallet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomChofer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCuartelEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCuartelReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomEmbalaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomEnvase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomEnvop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomEspecie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomEtiqueta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomExportador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomFacilitie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomFacilitieDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomFacilitiePallet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomGrpoVariedadEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomGrpoVariedadReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomNave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPLU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPredioEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPredioReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomProductorEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomProductorReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPuerto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPuertoDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomRecibidor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomTipoInspeccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomTipoInspeccionEnc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomTipoNave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomTipoTrat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomTransportista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomVariedadEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomVariedadReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEmbarcador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreGrupoCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreGrupoCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreGrupoProductor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreGrupoRecibidor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreMercadoNave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreNaviera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NotaVenta")
                        .HasColumnType("int");

                    b.Property<int?>("NroProceso")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCertificadoProductorEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCertificadoProductorReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObsGuia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObsSAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisNave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pallet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PesoBrutoAduana")
                        .HasColumnType("float");

                    b.Property<double>("PesoNeto")
                        .HasColumnType("float");

                    b.Property<int>("PlanillaDespacho")
                        .HasColumnType("int");

                    b.Property<int>("PlanillaOrdenEmbarque")
                        .HasColumnType("int");

                    b.Property<string>("ProvinciaProdEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinciaProdReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutAgenteAduana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutChofer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutExportador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutProductorEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutProductorReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutRecibidor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutTransportista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sellos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SemanaZarpe")
                        .HasColumnType("int");

                    b.Property<string>("Temperatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Termografo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCamion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCertificadoProductorEti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCertificadoProductorReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoContenedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMovimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPallet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalCajas")
                        .HasColumnType("int");

                    b.Property<int?>("TotalDet")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CloudFruitItems", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
