// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvexApi.Data;

#nullable disable

namespace ProvexApi.Migrations
{
    [DbContext(typeof(ProvexDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.Consignatario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodConsignatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomConsignatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asoex_Consignatario", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodEspecie")
                        .HasColumnType("int");

                    b.Property<int>("CodTipoEpecie")
                        .HasColumnType("int");

                    b.Property<string>("NomEspecie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asoex_Especie", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.Exportador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DvEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RutEmpresa")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Asoex_Exportador", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.Nave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodNave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomNave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoNave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asoex_Nave", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.PaisDestino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodPais")
                        .HasColumnType("int");

                    b.Property<int>("CodRegionPais")
                        .HasColumnType("int");

                    b.Property<string>("NomPais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asoex_PaisesDestino", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.Proceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaProceso")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraProceso")
                        .HasColumnType("time");

                    b.Property<int>("IdProceso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Asoex_Procesos");
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.ProcesoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodCondicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodConsignatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodEspecie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodPuertoDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodPuertoEmbarque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodRegionOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodVariedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrelativoViaje")
                        .HasColumnType("int");

                    b.Property<int>("IdProceso")
                        .HasColumnType("int");

                    b.Property<int>("NroOtro")
                        .HasColumnType("int");

                    b.Property<int>("PsdCantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("PsdTotKgNeto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RutExportador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempSeqNro")
                        .HasColumnType("int");

                    b.Property<int?>("pagina_api")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProceso");

                    b.ToTable("Asoex_ProcesoDetalles");
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.ProcesoViaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodNave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodPuertoArribo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodPuertoEmbarque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrelativoViaje")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaArribo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaZarpe")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProceso")
                        .HasColumnType("int");

                    b.Property<int>("NroOtro")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempSeqNro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProceso");

                    b.ToTable("Asoex_ProcesoViajes");
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.PuertoDestino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodCosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodPais")
                        .HasColumnType("int");

                    b.Property<string>("CodPuerto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPuerto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asoex_PuertosDestino", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.PuertoEmbarque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodPuerto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPuerto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asoex_PuertoEmbarque", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.RegionDestino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodRegionPais")
                        .HasColumnType("int");

                    b.Property<string>("NomRegionPais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asoex_RegionesDestino", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.RegionOrigen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodRegionOrigen")
                        .HasColumnType("int");

                    b.Property<string>("NomRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asoex_RegionOrigen", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.Semana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha2")
                        .HasColumnType("datetime2");

                    b.Property<int>("NroOtro")
                        .HasColumnType("int");

                    b.Property<int>("NroSemana")
                        .HasColumnType("int");

                    b.Property<int>("TempSeqNro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Asoex_Semana", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.Temporada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomTemporada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TempEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TempFechaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TempFechaHasta")
                        .HasColumnType("datetime2");

                    b.Property<int>("TempSeqNro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Asoex_Temporada", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.TipoEspecie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodTipoEpecie")
                        .HasColumnType("int");

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asoex_TipoEspecie", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.Variedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodEspecie")
                        .HasColumnType("int");

                    b.Property<int>("CodTipoEpecie")
                        .HasColumnType("int");

                    b.Property<int>("CodVariedad")
                        .HasColumnType("int");

                    b.Property<string>("NomVariedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asoex_Variedad", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("Component")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModuleId");

                    b.HasIndex("ParentId");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.RoleModule", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("RoleModule");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.SessionToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SessionTokens");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.UserModule", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("UserModule");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("ProvexApi.Entities.Packinglist.ViewPLPangea", b =>
                {
                    b.Property<string>("ArriPORT")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Arri PORT");

                    b.Property<decimal?>("CartonWeight")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("(21).Carton Weight");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Category");

                    b.Property<string>("Commodity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Commodity");

                    b.Property<string>("ContainerNbr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Container Nbr.");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Country of Origin");

                    b.Property<string>("DepPORT")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Dep PORT");

                    b.Property<DateTime?>("ETA")
                        .HasColumnType("datetime2")
                        .HasColumnName("ETA");

                    b.Property<DateTime?>("ETD")
                        .HasColumnType("datetime2")
                        .HasColumnName("ETD");

                    b.Property<string>("GrowerCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Grower Code");

                    b.Property<string>("GrowerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Grower Name");

                    b.Property<string>("Invoice")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Invoice");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Label");

                    b.Property<string>("LotNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Lot #");

                    b.Property<int?>("NBoxes")
                        .HasColumnType("int")
                        .HasColumnName("NBoxes");

                    b.Property<string>("PLU")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PLU");

                    b.Property<string>("Pack")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pack");

                    b.Property<string>("PackStyle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pack Style");

                    b.Property<DateTime?>("PackingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Packing Date");

                    b.Property<string>("PalletNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pallet number");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Product Code");

                    b.Property<string>("Producto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Producto");

                    b.Property<string>("Receiver")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Receiver");

                    b.Property<string>("ShippingCompany")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ShippingCompany");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Size");

                    b.Property<string>("ThermometerNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Thermometer No");

                    b.Property<string>("UsdaSeal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USDA Seal/ SAG Seal");

                    b.Property<string>("Variety")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Variety");

                    b.Property<string>("VesselName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Vessel Name");

                    b.Property<string>("VesselNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Vessel  Number");

                    b.ToTable((string)null);

                    b.ToView("View_PL_Pangea", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.SensiWatch.ThermographDevice", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IMEI")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrgUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlatformId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DeviceId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("SensiWatch_Devices");
                });

            modelBuilder.Entity("ProvexApi.Entities.SensiWatch.ThermographEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventId"));

                    b.Property<DateTime?>("ActivationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerShipmentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeviceTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TripId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("TripId");

                    b.HasIndex("DeviceId", "ReceivedAt");

                    b.ToTable("SensiWatch_Events");
                });

            modelBuilder.Entity("ProvexApi.Entities.SensiWatch.ThermographSensorReading", b =>
                {
                    b.Property<long>("SensorReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SensorReadingId"));

                    b.Property<DateTime?>("DeviceTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReceiveTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("SensorValue")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SensorReadingId");

                    b.HasIndex("EventId");

                    b.HasIndex("SensorType", "DeviceTime");

                    b.ToTable("SensiWatch_SensorReadings");
                });

            modelBuilder.Entity("ProvexApi.Entities.SensiWatch.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalTripId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SwpTripId")
                        .HasColumnType("int");

                    b.Property<string>("TrailerId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TripGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TripId");

                    b.HasIndex("InternalTripId");

                    b.HasIndex("SwpTripId")
                        .IsUnique();

                    b.ToTable("SensiWatch_Trips");
                });

            modelBuilder.Entity("ProvexApi.Models.API.ApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApiTokens", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Models.BackEnd.Logs.ServiceApiCallLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AuthSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("ClientIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponseSize")
                        .HasColumnType("int");

                    b.Property<string>("Snippet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceApiCallLogs", (string)null);
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.ProcesoDetalle", b =>
                {
                    b.HasOne("ProvexApi.Entities.ASOEX.Proceso", "Proceso")
                        .WithMany("Detalles")
                        .HasForeignKey("IdProceso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.ProcesoViaje", b =>
                {
                    b.HasOne("ProvexApi.Entities.ASOEX.Proceso", "Proceso")
                        .WithMany("Viajes")
                        .HasForeignKey("IdProceso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.Module", b =>
                {
                    b.HasOne("ProvexApi.Entities.Login.Module", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.RoleModule", b =>
                {
                    b.HasOne("ProvexApi.Entities.Login.Module", "Module")
                        .WithMany("RoleModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProvexApi.Entities.Login.Role", "Role")
                        .WithMany("RoleModules")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.RolePermission", b =>
                {
                    b.HasOne("ProvexApi.Entities.Login.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProvexApi.Entities.Login.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.UserModule", b =>
                {
                    b.HasOne("ProvexApi.Entities.Login.Module", "Module")
                        .WithMany("UserModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProvexApi.Entities.Login.User", "User")
                        .WithMany("UserModules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.UserRole", b =>
                {
                    b.HasOne("ProvexApi.Entities.Login.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProvexApi.Entities.Login.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProvexApi.Entities.SensiWatch.ThermographEvent", b =>
                {
                    b.HasOne("ProvexApi.Entities.SensiWatch.ThermographDevice", "Device")
                        .WithMany("Events")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProvexApi.Entities.SensiWatch.Trip", "Trip")
                        .WithMany("Events")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("ProvexApi.Entities.SensiWatch.ThermographSensorReading", b =>
                {
                    b.HasOne("ProvexApi.Entities.SensiWatch.ThermographEvent", "Event")
                        .WithMany("SensorReadings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ProvexApi.Entities.ASOEX.Proceso", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.Module", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleModules");

                    b.Navigation("UserModules");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.Role", b =>
                {
                    b.Navigation("RoleModules");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ProvexApi.Entities.Login.User", b =>
                {
                    b.Navigation("UserModules");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ProvexApi.Entities.SensiWatch.ThermographDevice", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("ProvexApi.Entities.SensiWatch.ThermographEvent", b =>
                {
                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("ProvexApi.Entities.SensiWatch.Trip", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
