// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvexApi.Data.Rossi;

#nullable disable

namespace ProvexApi.Migrations.RossiDb
{
    [DbContext(typeof(RossiDbContext))]
    partial class RossiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvexApi.Models.Rossi.ArchivoUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("ArchivoUrls");
                });

            modelBuilder.Entity("ProvexApi.Models.Rossi.RossiRoot+Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("aduanacodigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aduananombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("booking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_bl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_blnumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_bltipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_certificado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_correccionbl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_despacho_extranjero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_despacho_nacional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_duslegalizada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_errorplanilla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_etadestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_factura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_fullset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_origen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_tipoflete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_vistobueno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("consignatario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("despacho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dusdv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dusfecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dusnro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaenvioinforme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaestzarpe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechainicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechazarpe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horaenvioinforme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horaestzarpe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horainicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horazarpe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("motonave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("programa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("puertodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("puertoemb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sitio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("terminal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiponave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("valorflete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("valorfob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("valorliquidoretorno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("valorseguro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("viaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ws_bls")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("ProvexApi.Models.Rossi.RossiRoot+Embarque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("atmco2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("atmo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("atmosfera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("atributo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cajas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("condicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("costo_aforoaduana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("costo_consolidado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("costo_fzextraportuarias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("costo_guiaingresadazeal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("costo_ingresomultipuerto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("costo_inspeccionsag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("costo_instalacioncortina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("costo_latearrival")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("embalaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("embalajekb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("embalajekn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("embalajetipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("envio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("especie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("etiqueta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechacump")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaicon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaipto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechatcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechatemb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("guia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horacump")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horaicon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horaipto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horatcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horatemb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nrocontenedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("packing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pallemb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pallet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pallet1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pallet2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pallet3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pallet4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pallet5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pltxcjs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sello1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sello2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sello3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sello4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tara")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tcajas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tcontenedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tempsigno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("temptipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tempvalor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("termografo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("termografo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("termografo3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("termografo4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("termografo5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tkilosb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tkilosn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tpallet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transportista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("variedad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("venttipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ventvalor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("Embarques");
                });

            modelBuilder.Entity("ProvexApi.Models.Rossi.RossiRoot+Facturacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("f_cantidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_empresarut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_empresarutdv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_factura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_fechaemision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_fechavencimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_moneda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_monto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_servicionombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_valorobservado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("Facturaciones");
                });

            modelBuilder.Entity("ProvexApi.Models.Rossi.RossiRoot+PDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PalletId")
                        .HasColumnType("int");

                    b.Property<string>("p_atributo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_cajas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_calibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_calidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_codembalaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_embalaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_embalajet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_especie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_etiqueta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_guia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_kb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_kn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_packing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_productor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_variedad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PalletId");

                    b.ToTable("PDetalles");
                });

            modelBuilder.Entity("ProvexApi.Models.Rossi.RossiRoot+Pallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("p_camara")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_contenedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_nivel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_pallet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_temperatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_termografo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("Pallets");
                });

            modelBuilder.Entity("ProvexApi.Models.Rossi.ArchivoUrl", b =>
                {
                    b.HasOne("ProvexApi.Models.Rossi.RossiRoot+Documento", "Documento")
                        .WithMany("ArchivoUrls")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ProvexApi.Models.Rossi.RossiRoot+Embarque", b =>
                {
                    b.HasOne("ProvexApi.Models.Rossi.RossiRoot+Documento", "Documento")
                        .WithMany("Embarque")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ProvexApi.Models.Rossi.RossiRoot+Facturacion", b =>
                {
                    b.HasOne("ProvexApi.Models.Rossi.RossiRoot+Documento", "Documento")
                        .WithMany("Facturacion")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ProvexApi.Models.Rossi.RossiRoot+PDetalle", b =>
                {
                    b.HasOne("ProvexApi.Models.Rossi.RossiRoot+Pallet", "Pallet")
                        .WithMany("p_detalle")
                        .HasForeignKey("PalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pallet");
                });

            modelBuilder.Entity("ProvexApi.Models.Rossi.RossiRoot+Pallet", b =>
                {
                    b.HasOne("ProvexApi.Models.Rossi.RossiRoot+Documento", "Documento")
                        .WithMany("Pallets")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ProvexApi.Models.Rossi.RossiRoot+Documento", b =>
                {
                    b.Navigation("ArchivoUrls");

                    b.Navigation("Embarque");

                    b.Navigation("Facturacion");

                    b.Navigation("Pallets");
                });

            modelBuilder.Entity("ProvexApi.Models.Rossi.RossiRoot+Pallet", b =>
                {
                    b.Navigation("p_detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
